package cat.copernic.m03uf06review.hibernate_relational;
// Generated 15/12/2020 19:50:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organizacion generated by hbm2java
 */
public class Organizacion  implements java.io.Serializable {


     private Integer idOrg;
     private String nombreGrupo;
     private String descripcion;
     private Set personas = new HashSet(0);

    public Organizacion() {
    }

    public Organizacion(String nombreGrupo, String descripcion, Set personas) {
       this.nombreGrupo = nombreGrupo;
       this.descripcion = descripcion;
       this.personas = personas;
    }
   
    public Integer getIdOrg() {
        return this.idOrg;
    }
    
    public void setIdOrg(Integer idOrg) {
        this.idOrg = idOrg;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


