package cat.copernic.m03uf06review.hibernate_relational;
// Generated 12/12/2020 02:41:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String nombrePersona;
     private String apellidos;
     private String direccion;
     private Integer codigoPostal;
     private String ciudad;
     private Double altura;
     private Boolean fumador;
     private Date fechaNacimiento;
     private Set organizacionsForIdPersona2 = new HashSet(0);
     private Set organizacionsForIdPersona3 = new HashSet(0);
     private Set organizacionsForIdPersona1 = new HashSet(0);

    public Persona() {
    }

    public Persona(String nombrePersona, String apellidos, String direccion, Integer codigoPostal, String ciudad, Double altura, Boolean fumador, Date fechaNacimiento, Set organizacionsForIdPersona2, Set organizacionsForIdPersona3, Set organizacionsForIdPersona1) {
       this.nombrePersona = nombrePersona;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.altura = altura;
       this.fumador = fumador;
       this.fechaNacimiento = fechaNacimiento;
       this.organizacionsForIdPersona2 = organizacionsForIdPersona2;
       this.organizacionsForIdPersona3 = organizacionsForIdPersona3;
       this.organizacionsForIdPersona1 = organizacionsForIdPersona1;
    }

    public Persona(String nombrePersona, String apellidos, String direccion, Integer codigoPostal, String ciudad, Double altura, Boolean fumador, Date fechaNacimiento) {
        this.nombrePersona = nombrePersona;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.codigoPostal = codigoPostal;
        this.ciudad = ciudad;
        this.altura = altura;
        this.fumador = fumador;
        this.fechaNacimiento = fechaNacimiento;
    }
    
    
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public Boolean getFumador() {
        return this.fumador;
    }
    
    public void setFumador(Boolean fumador) {
        this.fumador = fumador;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getOrganizacionsForIdPersona2() {
        return this.organizacionsForIdPersona2;
    }
    
    public void setOrganizacionsForIdPersona2(Set organizacionsForIdPersona2) {
        this.organizacionsForIdPersona2 = organizacionsForIdPersona2;
    }
    public Set getOrganizacionsForIdPersona3() {
        return this.organizacionsForIdPersona3;
    }
    
    public void setOrganizacionsForIdPersona3(Set organizacionsForIdPersona3) {
        this.organizacionsForIdPersona3 = organizacionsForIdPersona3;
    }
    public Set getOrganizacionsForIdPersona1() {
        return this.organizacionsForIdPersona1;
    }
    
    public void setOrganizacionsForIdPersona1(Set organizacionsForIdPersona1) {
        this.organizacionsForIdPersona1 = organizacionsForIdPersona1;
    }




}


