package cat.copernic.m03uf06review.hibernate_relational;
// Generated 15/12/2020 19:50:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private Organizacion organizacion;
     private String nombrePersona;
     private String apellidos;
     private String direccion;
     private Integer codigoPostal;
     private String ciudad;
     private Double altura;
     private Boolean fumador;
     private Date fechaNacimiento;

    public Persona() {
    }

    public Persona(Organizacion organizacion, String nombrePersona, String apellidos, String direccion, Integer codigoPostal, String ciudad, Double altura, Boolean fumador, Date fechaNacimiento) {
       this.organizacion = organizacion;
       this.nombrePersona = nombrePersona;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.altura = altura;
       this.fumador = fumador;
       this.fechaNacimiento = fechaNacimiento;
    }

    public Persona(String nombrePersona, String apellidos, String direccion, Integer codigoPostal, String ciudad, Double altura, Boolean fumador, Date fechaNacimiento) {
        this.nombrePersona = nombrePersona;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.codigoPostal = codigoPostal;
        this.ciudad = ciudad;
        this.altura = altura;
        this.fumador = fumador;
        this.fechaNacimiento = fechaNacimiento;
    }
    
    
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public Boolean getFumador() {
        return this.fumador;
    }
    
    public void setFumador(Boolean fumador) {
        this.fumador = fumador;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }




}


