package cat.copernic.m03uf06review.hibernate;
// Generated 15/12/2020 19:50:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer idPersona;
     private String nombre;
     private String apellidos;
     private String direccion;
     private Integer codigoPostal;
     private String ciudad;
     private Double altura;
     private Boolean fumador;
     private Date fechaNacimiento;

    public Personas() {
    }

    public Personas(String nombre, String apellidos, String direccion, Integer codigoPostal, String ciudad, Double altura, Boolean fumador, Date fechaNacimiento) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.altura = altura;
       this.fumador = fumador;
       this.fechaNacimiento = fechaNacimiento;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public Boolean getFumador() {
        return this.fumador;
    }
    
    public void setFumador(Boolean fumador) {
        this.fumador = fumador;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }




}


